### ISSUE TITLE
crash app : Failed to call observer method

### ISSUE THREAD

**Issue by fukemy** [SanojPunchihewa/InAppUpdater#84]
hi, i just use 2 lines of code:
```
val mUpdateManager = UpdateManager.Builder(this).mode(UpdateManagerConstant.FLEXIBLE);
        mUpdateManager.start()
```

but got this crash:
```

2021-03-05 23:25:09.458 8683-8683/com.civix.link E/CustomActivityOnCrash: The previous app process crashed. This is the stack trace of the crash:
    java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:188)
        at com.sanojpunchihewa.updatemanager.UpdateManager.<init>(UpdateManager.java:49)
        at com.sanojpunchihewa.updatemanager.UpdateManager.Builder(UpdateManager.java:54)
        at com.civix.link.Screen.HomeScreen.checkUpdateApp(HomeScreen.kt:296)
        at com.civix.link.Screen.HomeScreen.access$checkUpdateApp(HomeScreen.kt:57)
        at com.civix.link.Screen.HomeScreen$getCurrentUserInfo$1.onSuccess(HomeScreen.kt:195)
        at com.civix.link.Network.ApiHelper$getData$1.onResponse(ApiHelper.kt:42)
        at com.androidnetworking.common.ANRequest.deliverSuccessResponse(ANRequest.java:727)
        at com.androidnetworking.common.ANRequest.access$6500(ANRequest.java:80)
        at com.androidnetworking.common.ANRequest$6.run(ANRequest.java:709)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.sanojpunchihewa.updatemanager.UpdateManager.mode' on a null object reference
        at com.sanojpunchihewa.updatemanager.UpdateManager.continueUpdate(UpdateManager.java:142)
        at com.sanojpunchihewa.updatemanager.UpdateManager.onResume(UpdateManager.java:252)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:188) 
        at com.sanojpunchihewa.updatemanager.UpdateManager.<init>(UpdateManager.java:49) 
        at com.sanojpunchihewa.updatemanager.UpdateManager.Builder(UpdateManager.java:54) 
        at com.civix.link.Screen.HomeScreen.checkUpdateApp(HomeScreen.kt:296) 
        at com.civix.link.Screen.HomeScreen.access$checkUpdateApp(HomeScreen.kt:57) 
        at com.civix.link.Screen.HomeScreen$getCurrentUserInfo$1.onSuccess(HomeScreen.kt:195) 
        at com.civix.link.Network.ApiHelper$getData$1.onResponse(ApiHelper.kt:42) 
        at com.androidnetworking.common.ANRequest.deliverSuccessResponse(ANRequest.java:727) 
        at com.androidnetworking.common.ANRequest.access$6500(ANRequest.java:80) 
        at com.androidnetworking.common.ANRequest$6.run(ANRequest.java:709) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8107) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
2021-03-05 23:25:09.555 8683-8683/com.civix.link W/Gralloc3: mapper 3.x is not supported

```

**Comment by KhunGame** [comment]
I got the same issue.

I solve it by calling this in onCreate()

`UpdateManager.Builder(this).mode(UpdateManagerConstant.FLEXIBLE);`

and call .start() later
